// Generates src/guide/content.generated.ts from the sim source of truth (CLASSES +
// TALENTS), so the Guide's class data never drifts from the game. Mirrors the
// esbuild-bundle pattern in scripts/export_loot_spreadsheet.mjs (never import raw .ts).
// Run via `npm run wiki:content`; the build runs it and the committed output is
// freshness-checked in tests/guide.test.ts. Deterministic: reads data, writes a file.
import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const outFile = path.join(root, 'src', 'guide', 'content.generated.ts');

const entrySource = `
  export { CLASSES, ABILITIES } from './src/sim/content/classes.ts';
  export { TALENTS } from './src/sim/content/talents.ts';
  export { ALL_CLASSES } from './src/sim/types.ts';
`;

const built = await esbuild.build({
  stdin: { contents: entrySource, resolveDir: root, sourcefile: 'wiki-content-entry.ts', loader: 'ts' },
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
  logLevel: 'silent',
});
const dataUrl = `data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`;
const { CLASSES, ABILITIES, TALENTS, ALL_CLASSES } = await import(dataUrl);

const ROLE_ORDER = ['tank', 'healer', 'dps'];
const hex = (n) => `#${(n >>> 0).toString(16).padStart(6, '0').slice(-6)}`;

// How many early, spoiler-safe abilities to surface as the "signature kit".
const SIGNATURE_COUNT = 6;

const classes = ALL_CLASSES.map((id) => {
  const def = CLASSES[id];
  const specs = (TALENTS[id]?.specs ?? []).map((s) => ({ name: s.name, role: s.role }));
  const roles = ROLE_ORDER.filter((r) => specs.some((s) => s.role === r));
  const signatureAbilities = (def.abilities ?? [])
    .slice(0, SIGNATURE_COUNT)
    .map((aid) => ({ id: aid, name: ABILITIES[aid]?.name ?? aid }));
  return { id, color: hex(def.color), resource: def.resourceType, roles, specs, signatureAbilities };
});

const header = `// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with \`npm run wiki:content\`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideClassSpec { name: string; role: GuideRole; }
export interface GuideSignatureAbility { id: string; name: string; }

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideSignatureAbility[];
}
`;

writeFileSync(outFile, `${header}\nexport const GUIDE_CLASSES: GuideClassInfo[] = ${JSON.stringify(classes, null, 2)};\n`);
// eslint-disable-next-line no-console
console.log(`generated src/guide/content.generated.ts (${classes.length} classes)`);
