// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with `npm run wiki:content`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideClassSpec { name: string; role: GuideRole; }
export interface GuideSignatureAbility { id: string; name: string; }

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideSignatureAbility[];
}

export const GUIDE_CLASSES: GuideClassInfo[] = [
  {
    "id": "warrior",
    "color": "#c79c6e",
    "resource": "rage",
    "roles": [
      "tank",
      "dps"
    ],
    "specs": [
      {
        "name": "Arms",
        "role": "dps"
      },
      {
        "name": "Fury",
        "role": "dps"
      },
      {
        "name": "Protection",
        "role": "tank"
      }
    ],
    "signatureAbilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      }
    ]
  },
  {
    "id": "paladin",
    "color": "#f58cba",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Holy",
        "role": "healer"
      },
      {
        "name": "Protection",
        "role": "tank"
      },
      {
        "name": "Retribution",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      }
    ]
  },
  {
    "id": "hunter",
    "color": "#abd473",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Beast Mastery",
        "role": "dps"
      },
      {
        "name": "Marksmanship",
        "role": "dps"
      },
      {
        "name": "Survival",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      }
    ]
  },
  {
    "id": "rogue",
    "color": "#fff569",
    "resource": "energy",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Assassination",
        "role": "dps"
      },
      {
        "name": "Combat",
        "role": "dps"
      },
      {
        "name": "Subtlety",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      }
    ]
  },
  {
    "id": "priest",
    "color": "#fffff0",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Discipline",
        "role": "healer"
      },
      {
        "name": "Holy",
        "role": "healer"
      },
      {
        "name": "Shadow",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      }
    ]
  },
  {
    "id": "shaman",
    "color": "#0070de",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Elemental",
        "role": "dps"
      },
      {
        "name": "Enhancement",
        "role": "dps"
      },
      {
        "name": "Restoration",
        "role": "healer"
      }
    ],
    "signatureAbilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      }
    ]
  },
  {
    "id": "mage",
    "color": "#69ccf0",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Arcane",
        "role": "dps"
      },
      {
        "name": "Fire",
        "role": "dps"
      },
      {
        "name": "Frost",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      }
    ]
  },
  {
    "id": "warlock",
    "color": "#9482c9",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Affliction",
        "role": "dps"
      },
      {
        "name": "Demonology",
        "role": "dps"
      },
      {
        "name": "Destruction",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      }
    ]
  },
  {
    "id": "druid",
    "color": "#ff7d0a",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Balance",
        "role": "dps"
      },
      {
        "name": "Feral",
        "role": "tank"
      },
      {
        "name": "Restoration",
        "role": "healer"
      }
    ],
    "signatureAbilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      }
    ]
  }
];
